### ISSUE TITLE
White space after uncomment.

### ISSUE THREAD

**Issue by blindFS** [tyru/caw.vim#25] opened 2015-04-19 01:43 UTC
After uncommenting a block containing empty lines, white spaces will occur.

**Comment by tyru** [comment] 2015-06-26 13:19
Please give me more details.

**Comment by tyru** [comment] 2016-03-18 16:34
ping @blindFS 
(Will close this issue next weekend if you do not reply)

**Comment by tyru** [comment] 2016-03-18 16:39
@blindFS I can't reproduce in `filetype=vim`.
What filetype did you use? (if you remember)

`gcc` or `gcui` on the following line will remove both a comment and a whitespace.

```viml
"[whitespace]
```

**Comment by tyru** [comment] 2016-03-18 16:45
Sorry for delay to reply... ;(

**Comment by tyru** [comment] 2016-03-27 17:02
> (Will close this issue next weekend if you do not reply)

closed.

**Closed by tyru** 2016-03-27 17:02 UTC
Labels: bug
